package lewitt

const (
	VendorID  = "29c2"
	ProductID = "0004"

	CardID   = "C2"
	CardName = "CONNECT 2"

	alsamPCMName = "lewitt_connect_2"

	alsamConfFile      = "90-lewitt-connect-2.conf"
	wpRuleFileBasename = "51-lewitt-ignore.lua"

	alsamSystemConfPath = "/etc/alsa/conf.d/" + alsamConfFile
	alsamUserConfPath   = "~/.config/alsa/asoundrc"

	wpSystemConfDir = "/etc/wireplumber/main.lua.d"
	wpUserConfDir   = "~/.config/wireplumber/main.lua.d"

	alsamSystemConfTemplate = `# Generated by dilctl — Lewitt CONNECT 2 setup
# Capture: 4ch hw -> 2ch (FL FR) via route (drops spurious ch 2,3)
# Playback: 2ch hw direct (headphone out)
pcm.%s {
    type asym
    playback.pcm {
        type plug
        slave.pcm "hw:%s,0"
    }
    capture.pcm {
        type plug
        slave.pcm {
            type route
            slave.pcm "hw:%s,0"
            slave.channels 4
            ttable.0.0 1
            ttable.1.1 1
        }
    }
}
ctl.%s {
    type hw
    card %s
}
`

	wpRuleTemplate = `-- Generated by dilctl — Lewitt CONNECT 2 setup
-- Prevents WirePlumber from managing this device so it stays free
-- for direct ALSA access (e.g. Audacity via the "%s" PCM).
-- Match by stable USB vendor/product ID (survives card index reshuffles).
table.insert(alsa_monitor.rules, {
  matches = {
    {
      { "device.vendor.id", "=", "0x29c2" },
      { "device.product.id", "=", "0x0004" },
    },
  },
  apply_properties = {
    ["device.disabled"] = true,
  },
})
`
)

type DeviceInfo struct {
	CardIndex    int
	CardID       string
	CardName     string
	VendorID     string
	ProductID    string
	Serial       string
	Manufacturer string
	Product      string
	Connected    bool
}

type StreamInfo struct {
	Format      string
	Channels    int
	Rates       []string
	Bits        int
	ChannelMap  string
	StreamState string
}

type CaptureStreamInfo struct {
	Stream StreamInfo
}

type PlaybackStreamInfo struct {
	Stream StreamInfo
}

type ConfigStatus struct {
	ALSAMInstalled    bool
	ALSAMPath         string
	WPIgnoreInstalled bool
	WPIgnorePath      string
}

type VerificationResult struct {
	CaptureOK     bool
	CaptureRMSDB  [2]float64
	CaptureError  string
	PlaybackOK    bool
	PlaybackError string
	WavFile       string
}
