package lewitt

const (
	VendorID  = "29c2"
	ProductID = "0004"

	CardID   = "C2"
	CardName = "CONNECT 2"

	alsamPCMName = "lewitt_connect_2"

	alsamConfFile      = "90-lewitt-connect-2.conf"
	wpRuleFileBasename = "51-lewitt-ignore.lua"
	wpRuleDisabledName = wpRuleFileBasename + ".disabled"

	alsamSystemConfPath = "/etc/alsa/conf.d/" + alsamConfFile
	alsamUserConfPath   = "~/.config/alsa/asoundrc"

	wpSystemConfDir = "/etc/wireplumber/main.lua.d"
	wpUserConfDir   = "~/.config/wireplumber/main.lua.d"

	alsamSystemConfTemplate = `# Generated by dilctl — Lewitt CONNECT 2 setup
# Capture: fixed-rate 4ch hw -> 2ch (FL FR) via route
# Playback: fixed-rate 2ch hw (headphone out)
pcm.%s {
    type asym
    playback.pcm {
        type plug
        slave.pcm {
            type plug
            slave.pcm "hw:%s,0"
            slave.format S32_LE
            slave.rate 48000
            slave.channels 2
        }
    }
    capture.pcm {
        type plug
        slave.pcm {
            type route
            slave.pcm {
                type plug
                slave.pcm "hw:%s,0"
                slave.format S32_LE
                slave.rate 48000
                slave.channels 4
            }
            slave.channels 4
            ttable.0.0 1
            ttable.1.1 1
        }
    }
}
ctl.%s {
    type hw
    card %s
}
`
	wpRuleTemplate = `-- Generated by dilctl — Lewitt CONNECT 2 setup
table.insert(alsa_monitor.rules, {
  matches = {{ { "device.vendor.id", "=", "0x29c2" }, { "device.product.id", "=", "0x0004" } }},
  apply_properties = { ["device.disabled"] = true },
})
`
)

type DeviceInfo struct {
	CardIndex     int
	CardID        string
	CardName      string
	VendorID      string
	ProductID     string
	Serial        string
	Manufacturer  string
	Product       string
	USBDevicePath string
	Connected     bool
}

type StreamInfo struct {
	Format      string
	Channels    int
	Rates       []string
	Bits        int
	ChannelMap  string
	StreamState string
}

type CaptureStreamInfo struct {
	Stream StreamInfo
}

type PlaybackStreamInfo struct {
	Stream StreamInfo
}

type ConfigStatus struct {
	ALSAMInstalled       bool
	ALSAMPath            string
	WPIgnoreInstalled    bool // Legacy generated rule still present.
	WPIgnorePath         string
	WPIgnoreDisabled     bool
	WPIgnoreDisabledPath string
}

type VerificationResult struct {
	CaptureOK     bool
	CaptureRMSDB  [2]float64
	CaptureError  string
	PlaybackOK    bool
	PlaybackError string
	WavFile       string
}
