package lewitt

const (
	VendorID  = "29c2"
	ProductID = "0004"

	CardID   = "C2"
	CardName = "CONNECT 2"

	alsamPCMName = "lewitt_connect_2"

	alsamConfFile      = "90-lewitt-connect-2.conf"
	wpRuleFileBasename = "51-lewitt-ignore.lua"
	wpRuleDisabledName = wpRuleFileBasename + ".disabled"

	alsamSystemConfPath = "/etc/alsa/conf.d/" + alsamConfFile
	alsamUserConfPath   = "~/.config/alsa/asoundrc"

	wpSystemConfDir = "/etc/wireplumber/main.lua.d"
	wpUserConfDir   = "~/.config/wireplumber/main.lua.d"

	alsamSystemConfTemplate = `# Generated by dilctl — Lewitt CONNECT 2 setup
# Capture: fixed-rate 4ch dsnoop -> 2ch (FL FR) via route
# Playback: fixed-rate 2ch dmix (headphone out)
pcm.%s_playback_dmix {
    type dmix
    ipc_key 1024
    ipc_key_add_uid true
    slave {
        pcm "hw:%s,0"
        format S32_LE
        rate 48000
        channels 2
    }
}
pcm.%s_capture_dsnoop {
    type dsnoop
    ipc_key 1025
    ipc_key_add_uid true
    slave {
        pcm "hw:%s,0"
        format S32_LE
        rate 48000
        channels 4
    }
}
pcm.%s_capture_route {
    type route
    slave.pcm "%s_capture_dsnoop"
    slave.channels 4
    ttable.0.0 1
    ttable.1.1 1
}
pcm.%s {
    type asym
    playback.pcm {
        type plug
        slave.pcm "%s_playback_dmix"
    }
    capture.pcm {
        type plug
        slave.pcm "%s_capture_route"
    }
}
ctl.%s {
    type hw
    card %s
}
`
	wpRuleTemplate = `-- Generated by dilctl — Lewitt CONNECT 2 setup
table.insert(alsa_monitor.rules, {
  matches = {{ { "device.vendor.id", "=", "0x29c2" }, { "device.product.id", "=", "0x0004" } }},
  apply_properties = { ["device.disabled"] = true },
})
`
)

type DeviceInfo struct {
	CardIndex     int
	CardID        string
	CardName      string
	VendorID      string
	ProductID     string
	Serial        string
	Manufacturer  string
	Product       string
	USBDevicePath string
	Connected     bool
}

type StreamInfo struct {
	Format      string
	Channels    int
	Rates       []string
	Bits        int
	ChannelMap  string
	StreamState string
}

type CaptureStreamInfo struct {
	Stream StreamInfo
}

type PlaybackStreamInfo struct {
	Stream StreamInfo
}

type ConfigStatus struct {
	ALSAMInstalled       bool
	ALSAMPath            string
	WPIgnoreInstalled    bool // Legacy generated rule still present.
	WPIgnorePath         string
	WPIgnoreDisabled     bool
	WPIgnoreDisabledPath string
}

type VerificationResult struct {
	CaptureOK     bool
	CaptureRMSDB  [2]float64
	CaptureError  string
	PlaybackOK    bool
	PlaybackError string
	WavFile       string
}
